package gui;



import dao.AlunoDAO;
import dao.BD;
import entities.Aluno;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author stepgalvao
 */
public class FrameMain extends javax.swing.JFrame {

    BD bd ;
    
    /**
     * Creates new form FrameMain
     */
    public FrameMain() {
        aluno = new Aluno();
        alunos =  new ArrayList<>();
        try {
            bd = new BD();
        } catch (SQLException ex) {
            Logger.getLogger(FrameMain.class.getName()).log(Level.SEVERE, null, ex);
        }
        initComponents();
        updateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuPopup = new javax.swing.JPopupMenu();
        exibirMenu = new javax.swing.JMenuItem();
        alterarMenu = new javax.swing.JMenuItem();
        removerMenu = new javax.swing.JMenuItem();
        adicionarButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        alunosTable = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        exportarMenu = new javax.swing.JMenuItem();
        importarMenu = new javax.swing.JMenuItem();

        menuPopup.setLabel("Menu");

        exibirMenu.setText("Exibir");
        exibirMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exibirMenuActionPerformed(evt);
            }
        });
        menuPopup.add(exibirMenu);

        alterarMenu.setText("Alterar");
        alterarMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarMenuActionPerformed(evt);
            }
        });
        menuPopup.add(alterarMenu);

        removerMenu.setText("Remover");
        removerMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removerMenuActionPerformed(evt);
            }
        });
        menuPopup.add(removerMenu);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        adicionarButton.setText("Adicionar");
        adicionarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adicionarButtonActionPerformed(evt);
            }
        });

        jScrollPane2.setBorder(javax.swing.BorderFactory.createTitledBorder("Lista de alunos"));

        alunosTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Matricula"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        alunosTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableSelected(evt);
            }
        });
        jScrollPane2.setViewportView(alunosTable);

        jMenu1.setText("File");

        exportarMenu.setText("Exportar");
        exportarMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportarMenuActionPerformed(evt);
            }
        });
        jMenu1.add(exportarMenu);

        importarMenu.setText("Importar");
        importarMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                importarMenuActionPerformed(evt);
            }
        });
        jMenu1.add(importarMenu);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 708, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(adicionarButton)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(adicionarButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void adicionarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adicionarButtonActionPerformed
        this.aluno = new Aluno();
        
        AlunoForm alunoForm = new AlunoForm(this, aluno);
        alunoForm.setVisible(true);
        alunoForm.dispose();
        if (aluno.getMatricula() != 0) {
            //alunos.add(aluno);
            bd.insertAluno(aluno);
        }
            
        updateTable();
    }//GEN-LAST:event_adicionarButtonActionPerformed

    private void tableSelected(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableSelected

        if(evt.getButton()==3 && (alunosTable.getSelectedRow()!=-1)){
            menuPopup.show(alunosTable, evt.getX(), evt.getY());
        }
                
    }//GEN-LAST:event_tableSelected

    private void exibirMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exibirMenuActionPerformed
        int n = alunosTable.getSelectedRow();
        aluno = alunos.get(n);
        AlunoForm alunoForm = new AlunoForm(this, aluno);
        alunoForm.setEditable(false);
        alunoForm.setVisible(true);
    }//GEN-LAST:event_exibirMenuActionPerformed

    private void alterarMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarMenuActionPerformed
        int n = alunosTable.getSelectedRow();
        aluno = alunos.get(n);
        AlunoForm alunoForm = new AlunoForm(this, aluno);
        alunoForm.setVisible(true);
        alunos.set(n, aluno);
        updateTable();
    }//GEN-LAST:event_alterarMenuActionPerformed

    private void removerMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removerMenuActionPerformed
        int n = alunosTable.getSelectedRow();
        alunos.remove(n);
        updateTable();
        
        
    }//GEN-LAST:event_removerMenuActionPerformed

    private void exportarMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportarMenuActionPerformed
        String s = JOptionPane.showInputDialog("Digite o nome do arquivo");
        try{
            AlunoDAO alunoDAO = new AlunoDAO(s);
            for (Aluno aluno : alunos) {
                alunoDAO.insert(aluno);
            }
        } catch (FileNotFoundException ex) {
            JOptionPane.showMessageDialog(this,"Arquivo não criado");
        }
            
        
    }//GEN-LAST:event_exportarMenuActionPerformed

    private void importarMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_importarMenuActionPerformed
        try {
            String n = JOptionPane.showInputDialog("Digite o nome do arquivo de importação");
            alunos = AlunoDAO.selectAll(n);
        } catch (IOException ex) {
            Logger.getLogger(FrameMain.class.getName()).log(Level.SEVERE, null, ex);
        }
        updateTable();        
    }//GEN-LAST:event_importarMenuActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameMain().setVisible(true);
            }
        });
    }
    private void updateTable(){
        DefaultTableModel tableModel=  (DefaultTableModel) alunosTable.getModel();
        tableModel.setNumRows(0);
        alunos = bd.selectAll();
        for(Aluno a : alunos ){
            tableModel.addRow(new String[]{a.getNome(),String.valueOf(a.getMatricula())});
            System.out.println("add");
        }
        alunosTable.setModel(tableModel);
    }
    
    private Aluno aluno;
    private List<Aluno> alunos ;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adicionarButton;
    private javax.swing.JMenuItem alterarMenu;
    private javax.swing.JTable alunosTable;
    private javax.swing.JMenuItem exibirMenu;
    private javax.swing.JMenuItem exportarMenu;
    private javax.swing.JMenuItem importarMenu;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPopupMenu menuPopup;
    private javax.swing.JMenuItem removerMenu;
    // End of variables declaration//GEN-END:variables
}
